### PR TITLE
Add aas-2021 Workshop Folder and Files

### PR DESCRIPTION
**Pull request by advait-zx**
This PR introduces a new folder named aas-2021 to the repository, which will contain archived content from the AAS 2021 SunPy workshop. The folder is created to organize and store workshop materials, ensuring the history of the content is preserved and accessible for future reference.

### CODE REVIEW

**Comment by advait-zx** [comment]
check if it works

**Comment by nabobalis** [comment]
Thanks for the PR but I would also want the entire history of that repo to be added via this PR instead of just a new commit.

The aas-2021 repository has authorship that I want preserved.

**Comment by advait-zx** [comment]
How should I preserve repository history?
I mean what command should I use to preserve history.

**Comment by nabobalis** [comment]
That I don't know, it is not something I have done myself before but I have seen done by others.

I am not sure if stackoverflow has the answer for this case.

**Pull request closed without merging**
