### PR TITLE
Major cleanup

### PR DESCRIPTION
**Pull request by ehsteve**
This is a major cleanup of this repository to make it act like an index of all tutorials and materials available.

### CODE REVIEW

**Comment by Cadair** [comment]
This generally looks awesome. I like the directory based layout and the index in the readme :+1: 

I think it would be worth expanding the purpose of the repo a little bit, along the lines of this is an archive of previous tutorials and not a resource for people learning the current state of SunPy.

**Review by Cadair — APPROVED** [review]

**Comment by mbobra** [comment]
Looks good! I would suggest a standard naming convention.

**Comment by ehsteve** [comment]
@mbobra you mean a standard naming convention for the notebooks?

**Comment by mbobra** [comment]
Sorry @ehsteve for the delay -- yes I mean both for the notebooks (e.g. YYYY-MM-DD_MeetingName_MeetingLocation_NotebookTopic.ipynb) and for the folders (e.g. YYYY_MeetingName_MeetingLocation). Also maybe it is worth it to move [2016SPD-Python-SunPy](https://github.com/sunpy/2016SPD-Python-SunPy) into [2016_spd](https://github.com/sunpy/tutorial-notebooks/tree/master/2016_spd) and the same for 2017, so there is one consistent place to look for tutorial notebooks.

**Comment by ehsteve** [comment]
@mbobra that's probably a good idea. I've created an issue and assigned you to it. I hope you don't mind!

**Comment by mbobra** [comment]
No worries @ehsteve -- I will do it!

**Pull request merged**
