### PR TITLE
Added SDO 2018 Workshop Tutorial

### PR DESCRIPTION
**Pull request by MSKirk**
Michael Kirk, Monica Bobra, Will Barnes 
Thursday November 1st, 2018, 16h

SunPy is a community supported Python package for solar physics. Since its origin in 2011, SunPy has matured from a collection of useful routines into a robust platform for scientific discovery. This tutorial will walk through the major components of SunPy: data acquisition with FIDO, image analysis with Map, time series analysis with TimeSeries, and general Utilities that will aid your data exploration. We will conclude with a discussion of what to look forward to in SunPy version 1.0, which is expected to be released in 2019. This tutorial expects the attendees to have a basic familiarity with python, but will walk through the SunPy routines and give specific examples of where SunPy can help your current research.

### CODE REVIEW

**Comment by mbobra** [comment]
hey @Cadair @nabobalis : can someone approve this PR? @MSKirk put this tutorial together for the SDO18 workshop next week. Thanks!

**Comment by nabobalis** [comment]
@mbobra, you mean to merge in the PR or an actual review of the notebook?

If it is the latter, I don't have write access. I hope that @Cadair or @dpshelio does.

**Comment by mbobra** [comment]
@nabobalis I'm asking for the former -- to merge in the PR. @MSKirk, @wtbarnes, and I reviewed the actual content of the notebook and it works fine. So I would considered the notebook reviewed.

**Comment by nabobalis** [comment]
Ah ok,  @Cadair is having dinner but I will send him a message to do something.

**Comment by mbobra** [comment]
@nabobalis Thanks! :)

**Comment by wtbarnes** [comment]
Might be convenient if at least one of the three of us had a commit bit for this repo

**Comment by Cadair** [comment]
sorry for the delay you should all have write access now.

**Comment by wtbarnes** [comment]
Thanks @Cadair!

**Pull request merged**
